// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class DulceFacilDBContext : DbContext
{
    public DulceFacilDBContext()
    {
    }

    public DulceFacilDBContext(DbContextOptions<DulceFacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bitacora_Eventos> Bitacora_Eventos { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Conductor> Conductor { get; set; }

    public virtual DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }

    public virtual DbSet<Entrega> Entrega { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Ruta> Ruta { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Vehiculo> Vehiculo { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-TIMGTUL5\\SQLEXPRESS01;Initial Catalog=DulceFacilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bitacora_Eventos>(entity =>
        {
            entity.HasKey(e => e.ID_Evento).HasName("PK__Bitacora__929BD0C1C6A5A014");

            entity.Property(e => e.Fecha_Hora)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.UsuarioNavigation).WithMany(p => p.Bitacora_Eventos)
                .HasForeignKey(d => d.Usuario)
                .HasConstraintName("FK__Bitacora___Usuar__5165187F");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ID_Cliente).HasName("PK__Cliente__E005FBFFA2580F6C");

            entity.Property(e => e.Direccion).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(15);
            entity.Property(e => e.Zona).HasMaxLength(50);
        });

        modelBuilder.Entity<Conductor>(entity =>
        {
            entity.HasKey(e => e.ID_Conductor).HasName("PK__Conducto__24F451ABDB4F60F4");

            entity.Property(e => e.Estado).HasMaxLength(20);
            entity.Property(e => e.Licencia).HasMaxLength(50);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(15);
        });

        modelBuilder.Entity<Detalle_Pedido>(entity =>
        {
            entity.HasKey(e => new { e.ID_Pedido, e.ID_Producto }).HasName("PK__Detalle___C4C2927EF28C8A4E");

            entity.Property(e => e.Subtotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_PedidoNavigation).WithMany(p => p.Detalle_Pedido)
                .HasForeignKey(d => d.ID_Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_P__ID_Pe__3F466844");

            entity.HasOne(d => d.ID_ProductoNavigation).WithMany(p => p.Detalle_Pedido)
                .HasForeignKey(d => d.ID_Producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_P__ID_Pr__403A8C7D");
        });

        modelBuilder.Entity<Entrega>(entity =>
        {
            entity.HasKey(e => e.ID_Entrega).HasName("PK__Entrega__FEDACB7F605AE028");

            entity.Property(e => e.Estado_Entrega).HasMaxLength(20);
            entity.Property(e => e.Hora_Entrega).HasColumnType("datetime");

            entity.HasOne(d => d.ID_PedidoNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.ID_Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entrega__ID_Pedi__49C3F6B7");

            entity.HasOne(d => d.ID_RutaNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.ID_Ruta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entrega__ID_Ruta__4AB81AF0");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.ID_Pedido).HasName("PK__Pedido__FD76807051462C0A");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_ClienteNavigation).WithMany(p => p.Pedido)
                .HasForeignKey(d => d.ID_Cliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pedido__ID_Clien__3C69FB99");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.ID_Producto).HasName("PK__Producto__9B4120E2709752AC");

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Ruta>(entity =>
        {
            entity.HasKey(e => e.ID_Ruta).HasName("PK__Ruta__4851E68BE4A987EB");

            entity.Property(e => e.Estado).HasMaxLength(20);
            entity.Property(e => e.Vehiculo_Asignado).HasMaxLength(10);
            entity.Property(e => e.Zona).HasMaxLength(50);

            entity.HasOne(d => d.ID_ConductorNavigation).WithMany(p => p.Ruta)
                .HasForeignKey(d => d.ID_Conductor)
                .HasConstraintName("FK__Ruta__ID_Conduct__46E78A0C");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.ID_Usuario).HasName("PK__Usuario__DE4431C59CFD7BB9");

            entity.HasIndex(e => e.Email, "UQ__Usuario__A9D1053491076058").IsUnique();

            entity.Property(e => e.Contrasena).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre).HasMaxLength(100);
            entity.Property(e => e.Rol).HasMaxLength(50);
        });

        modelBuilder.Entity<Vehiculo>(entity =>
        {
            entity.HasKey(e => e.ID_Vehiculo).HasName("PK__Vehiculo__FEFD7E331F93DC5E");

            entity.Property(e => e.Estado).HasMaxLength(20);
            entity.Property(e => e.Placa)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Tipo).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    internal DbSet<T> dbSet<T>()
    {
        throw new NotImplementedException();
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}