// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Bitacora_Eventos
{
    public int ID_Evento { get; set; }

    public DateTime? Fecha_Hora { get; set; }

    public int? Usuario { get; set; }

    public string Descripcion { get; set; }

    public virtual Usuario UsuarioNavigation { get; set; }
}