// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int ID_Cliente { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Zona { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}