// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Conductor
{
    public int ID_Conductor { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Licencia { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();
}