// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Detalle_Pedido
{
    public int ID_Pedido { get; set; }

    public int ID_Producto { get; set; }

    public int Cantidad { get; set; }

    public decimal? Subtotal { get; set; }

    public virtual Pedido ID_PedidoNavigation { get; set; }

    public virtual Producto ID_ProductoNavigation { get; set; }
}