// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Entrega
{
    public int ID_Entrega { get; set; }

    public int ID_Pedido { get; set; }

    public int ID_Ruta { get; set; }

    public DateTime? Hora_Entrega { get; set; }

    public string Estado_Entrega { get; set; }

    public byte[] Firma_Cliente { get; set; }

    public virtual Pedido ID_PedidoNavigation { get; set; }

    public virtual Ruta ID_RutaNavigation { get; set; }
}