// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedido
{
    public int ID_Pedido { get; set; }

    public DateTime Fecha { get; set; }

    public string Estado { get; set; }

    public decimal? Total { get; set; }

    public int ID_Cliente { get; set; }

    public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; } = new List<Detalle_Pedido>();

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Cliente ID_ClienteNavigation { get; set; }
}