// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Ruta
{
    public int ID_Ruta { get; set; }

    public DateOnly Fecha { get; set; }

    public string Estado { get; set; }

    public string Zona { get; set; }

    public string Vehiculo_Asignado { get; set; }

    public int? ID_Conductor { get; set; }

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Conductor ID_ConductorNavigation { get; set; }
}