// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Vehiculo
{
    public int ID_Vehiculo { get; set; }

    public string Placa { get; set; }

    public string Tipo { get; set; }

    public int? Capacidad { get; set; }

    public string Estado { get; set; }
}